### ISSUE TITLE
Write quickstart guide

### ISSUE THREAD

**Issue by dealingwith** [Karun-A3E/notion2Export#1]
With a quick reading of the code, it's unclear exactly what's required to get the CLI to successfully run. I could do a more thorough reading of the code and try a few things, but I thought I'd cut this ticket for writing up a quickstart guide to help someone new coming to the project at this stage. [Here's an example of the quickstart for my Notionpaper project](https://github.com/dealingwith/notionpaper#quickstart).

**Comment by Karun-A3E** [comment]
A quickstart guide has been published, that being said the tool is still in dev. For the time being, pages can be exported but the sorting, querying and exporting has not been implemented

**Comment by dealingwith** [comment]
Looks good! I get an error on the `notion setup required` step:

```
~/code/notion2Export (main*) » node notion setup required
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/home/danielmiller/code/notion2Export/notion'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.7.0
```

**Comment by Karun-A3E** [comment]
Once npm link has been perform no need to use node anymore. Command is going to be notion setup required

**Comment by dealingwith** [comment]
I pulled latest and re-applied the steps and it ran this time. :+1: 

I'm having issues with `notion db read` passing either `name` or `id` but those are separate issues. Is that functionality still in progress or should I cut tickets with my results?

**Comment by Karun-A3E** [comment]
Once the append is done, check the databasekey.json in the .cache folder, based on the name can you try again. I have been using it on my side, and have not found any issues with as of now
